spring:
  application:
    name: sunboat-admin-web

# Nacos registry + Dubbo configuration (example defaults: nacos://127.0.0.1:8848, Dubbo 20880)
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20880
